CREATE TABLE work_save_intent (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    file_id BIGINT NOT NULL,
    expected_revision BIGINT NOT NULL,
    before_key VARCHAR(500) NOT NULL,
    before_sha256 VARCHAR(64) NOT NULL,
    target_key VARCHAR(500) NOT NULL,
    target_size BIGINT NOT NULL,
    request_sha256 VARCHAR(64) NOT NULL,
    target_sha256 VARCHAR(64),
    target_etag VARCHAR(255),
    recovered_file_id BIGINT,
    task_id VARCHAR(64) NOT NULL,
    file_name TEXT NOT NULL,
    file_type VARCHAR(50),
    model_snapshot_id VARCHAR(36),
    run_mode VARCHAR(16) NOT NULL,
    status VARCHAR(24) NOT NULL,
    attempts INT NOT NULL,
    next_attempt_at DATETIME(6),
    last_error_code VARCHAR(64),
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    CONSTRAINT fk_work_save_owner FOREIGN KEY (owner_id) REFERENCES app_user(id),
    CONSTRAINT uk_work_save_target UNIQUE (owner_id, target_key),
    CONSTRAINT uk_work_save_task UNIQUE (owner_id, task_id),
    INDEX idx_work_save_due (owner_id,status,next_attempt_at)
) ENGINE=InnoDB;
