FROM mysql:8.4@sha256:6ea90827b1100f8f2ae306a539f86d2c264a26ed435a2a9f75551dd5c3aeb242
USER 0:0
COPY deploy/mysql-entrypoint.sh /opt/coffer-entrypoint.sh
RUN chmod 0555 /opt/coffer-entrypoint.sh
ENTRYPOINT ["/opt/coffer-entrypoint.sh"]
CMD ["mysqld"]
