#!/bin/bash
set -euo pipefail
# Executed as the official mysql service user after entrypoint ownership setup.
chmod 0700 /var/lib/mysql
# Only the official MySQL entrypoint executes this on a brand-new data volume.
# Hex passwords are generated by prepare.py; no SQL interpolation of arbitrary input.
app=$COFFER_DB_APP_PASSWORD
migrate=$COFFER_DB_MIGRATE_PASSWORD
[[ "$app" =~ ^[a-f0-9]{64}$ && "$migrate" =~ ^[a-f0-9]{64}$ ]]
MYSQL_PWD="$MYSQL_ROOT_PASSWORD" mysql --protocol=socket -uroot <<SQL
CREATE USER 'coffer_app'@'%' IDENTIFIED BY '$app' REQUIRE SSL;
GRANT SELECT, INSERT, UPDATE, DELETE ON coffer.* TO 'coffer_app'@'%';
CREATE USER 'coffer_migrate'@'%' IDENTIFIED BY '$migrate' REQUIRE SSL;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES, DROP ON coffer.* TO 'coffer_migrate'@'%';
SQL
unset COFFER_DB_APP_PASSWORD COFFER_DB_MIGRATE_PASSWORD app migrate
