package com.coffer.entity;

import com.coffer.auth.domain.TenantOwnedEntity;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;

/** The public token is generated by the server; possession of it grants no access. */
@Entity
@Table(name = "chat_session")
@Getter
@NoArgsConstructor
public class ChatSession extends TenantOwnedEntity {
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "session_id", nullable = false, unique = true, length = 36)
    private String sessionId;

    public ChatSession(String sessionId) { this.sessionId = sessionId; }
}
