package com.coffer.desktop;

import org.springframework.context.annotation.*;
import org.springdoc.core.customizers.OpenApiCustomizer;
import io.swagger.v3.core.converter.ModelConverters;

/** Desktop endpoints stay disabled in dev; their DTO is still generated by the isolated dev contract. */
@Configuration(proxyBeanMethods = false) @Profile("dev & !desktop & !prod")
public class WorkCopyContractConfiguration {
    @Bean OpenApiCustomizer workCopyContract() {
        return api -> ModelConverters.getInstance().readAll(WorkCopyService.View.class)
                .forEach((name, schema) -> api.getComponents().addSchemas(name, schema));
    }
}
