ALTER TABLE file_metadata ADD revision BIGINT NOT NULL DEFAULT 0;
ALTER TABLE file_metadata ADD content_etag VARCHAR(255);

CREATE TABLE governance_preview_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    preview_id VARCHAR(64) NOT NULL,
    preview_source VARCHAR(32) NOT NULL,
    run_mode VARCHAR(16) NOT NULL,
    request_id VARCHAR(128) NOT NULL,
    created_by VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    total_count INT NOT NULL DEFAULT 0,
    ready_count INT NOT NULL DEFAULT 0,
    failed_count INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    confirmed_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    CONSTRAINT uk_governance_preview_batch_preview_id UNIQUE (preview_id),
    CONSTRAINT uk_governance_preview_batch_request_id UNIQUE (request_id)
);

CREATE INDEX idx_governance_preview_batch_status_expires
    ON governance_preview_batch(status, expires_at);
CREATE INDEX idx_governance_preview_batch_created
    ON governance_preview_batch(created_at);

CREATE TABLE governance_preview_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    preview_id VARCHAR(64) NOT NULL,
    file_id BIGINT NOT NULL,
    source_revision BIGINT NOT NULL DEFAULT 0,
    source_path VARCHAR(500),
    source_file_name TEXT,
    source_category VARCHAR(30),
    source_etag VARCHAR(255),
    source_size BIGINT,
    suggested_file_name TEXT,
    suggested_category VARCHAR(30),
    suggested_path VARCHAR(500),
    suggested_summary TEXT,
    suggested_tags TEXT,
    analysis_model VARCHAR(128),
    analysis_mode VARCHAR(16),
    status VARCHAR(32) NOT NULL,
    skip_reason VARCHAR(255),
    error_code VARCHAR(64),
    error_message TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    confirmed_at TIMESTAMP,
    CONSTRAINT uk_governance_preview_item_preview_file UNIQUE (preview_id, file_id)
);

CREATE INDEX idx_governance_preview_item_preview_status
    ON governance_preview_item(preview_id, status);
CREATE INDEX idx_governance_preview_item_file_created
    ON governance_preview_item(file_id, created_at);
