CREATE TABLE governance_compensation_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_key VARCHAR(160) NOT NULL,
    batch_id VARCHAR(64) NOT NULL,
    item_id BIGINT NOT NULL,
    action VARCHAR(40) NOT NULL,
    status VARCHAR(20) NOT NULL,
    object_path VARCHAR(500),
    attempts INT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP,
    last_error TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP,
    CONSTRAINT uk_governance_compensation_task_key UNIQUE (task_key)
);
CREATE INDEX idx_governance_compensation_due ON governance_compensation_task(status, next_attempt_at);
CREATE INDEX idx_governance_compensation_batch ON governance_compensation_task(batch_id, created_at);
