CREATE TABLE model_runtime_endpoint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_mode VARCHAR(16) NOT NULL,
    capability VARCHAR(16) NOT NULL,
    base_url VARCHAR(512) NOT NULL,
    model_name VARCHAR(128) NOT NULL,
    encrypted_api_key TEXT,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_model_runtime_endpoint_mode_capability UNIQUE (run_mode, capability)
);
