CREATE TABLE archive_object_name_allocator_lock (
    id BIGINT PRIMARY KEY,
    lock_name VARCHAR(64) NOT NULL,
    CONSTRAINT uk_archive_object_name_allocator_lock_name UNIQUE (lock_name)
);

INSERT INTO archive_object_name_allocator_lock (id, lock_name)
VALUES (1, 'GLOBAL');

CREATE TABLE archive_object_name_reservation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_date DATE NOT NULL,
    category_slug VARCHAR(64) NOT NULL,
    normalized_file_name VARCHAR(512) NOT NULL,
    sequence_number INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_archive_object_name_reservation
        UNIQUE (business_date, category_slug, normalized_file_name, sequence_number)
);

CREATE INDEX idx_archive_object_name_reservation_lookup
    ON archive_object_name_reservation (business_date, category_slug, normalized_file_name);
