ALTER TABLE user_model_credential DROP CONSTRAINT pk_user_model_credential;
ALTER TABLE user_model_credential ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
ALTER TABLE user_model_credential ADD CONSTRAINT uk_user_credential_owner_provider UNIQUE (owner_id, provider);
