CREATE TABLE async_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id VARCHAR(64) NOT NULL,
    file_name VARCHAR(255),
    status VARCHAR(20) NOT NULL,
    progress INTEGER,
    result TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT uk_async_task_task_id UNIQUE (task_id)
);

CREATE TABLE chat_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL,
    user_message TEXT,
    ai_response TEXT,
    timestamp TIMESTAMP
);

CREATE TABLE file_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name TEXT NOT NULL,
    file_size BIGINT NOT NULL,
    file_type VARCHAR(50),
    storage_path VARCHAR(500),
    upload_time TIMESTAMP,
    summary TEXT,
    status VARCHAR(20) NOT NULL,
    task_id VARCHAR(64),
    category VARCHAR(30),
    archived BOOLEAN NOT NULL
);

CREATE TABLE tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_name VARCHAR(255) NOT NULL,
    category VARCHAR(50),
    created_at TIMESTAMP,
    CONSTRAINT uk_tag_tag_name UNIQUE (tag_name)
);

CREATE TABLE file_tag_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    confirmation_status VARCHAR(20) NOT NULL,
    confirmed_at TIMESTAMP,
    confirmation_note VARCHAR(500),
    CONSTRAINT uk_file_tag_mapping_file_tag UNIQUE (file_id, tag_id)
);

CREATE TABLE model_call_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(128),
    user_message TEXT,
    ai_response TEXT,
    prompt_tokens INTEGER,
    completion_tokens INTEGER,
    total_tokens INTEGER,
    retry_count INTEGER,
    response_time_ms BIGINT,
    call_time TIMESTAMP NOT NULL,
    model_name VARCHAR(128),
    status VARCHAR(20),
    error_message TEXT
);
