CREATE TABLE memory_deletion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES app_user(id),
    session_id VARCHAR(36) NOT NULL
);
CREATE INDEX idx_memory_deletion_owner ON memory_deletion(owner_id);
