CREATE TABLE runtime_alert (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 code VARCHAR(96) NOT NULL, severity VARCHAR(16) NOT NULL,
 first_seen TIMESTAMP NOT NULL, last_seen TIMESTAMP NOT NULL, resolved_at TIMESTAMP
);
CREATE INDEX idx_runtime_alert_active ON runtime_alert(code,resolved_at);
CREATE TABLE secret_rotation_event (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 key_id VARCHAR(16) NOT NULL, verified_count BIGINT NOT NULL, rewritten_count BIGINT NOT NULL, completed_at TIMESTAMP NOT NULL
);
CREATE TABLE secret_rotation_lock (id INT PRIMARY KEY);
INSERT INTO secret_rotation_lock(id) VALUES(1);
