CREATE TABLE chat_memory (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 owner_id BIGINT NOT NULL,
 session_id VARCHAR(36) NOT NULL,
 envelope TEXT NOT NULL,
 expires_at TIMESTAMP NOT NULL,
 CONSTRAINT uq_chat_memory_owner_session UNIQUE(owner_id, session_id)
);
CREATE INDEX idx_chat_memory_expiry ON chat_memory(owner_id, expires_at);
